import type { Metadata } from "next";
import "./globals.css";
import { RedirectToSignIn, SignedIn } from "@clerk/nextjs";
import { SignedOut } from "@clerk/nextjs";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
          <SignedIn>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex flex-col w-full">
                <div className="flex items-center">
                  <SidebarTrigger />
                  <p>name and Logo</p>
                </div>
                <div className="flex w-full justify-center">
                  {children}
                </div>
              </main>
            </SidebarProvider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
